### ISSUE TITLE
Cameo PopOS Gtk theme is not good in Pop Shop

### ISSUE THREAD

**Issue by sandangel** [paullinuxthemer/cameo#1]
![image](https://user-images.githubusercontent.com/22189661/85221809-e8a77400-b3f1-11ea-8211-a4c517b04f97.png)

I tried the cameo popos gtk theme. It's really nice, only need some more works to fix issues on Pop Shop then it will be perfect

**Comment by paullinuxthemer** [comment]
Is a flatpak application, so themes that are not compatible for flatpak do not work

**Comment by sandangel** [comment]
I don't think Pop Shop is a flatpak application. @paullinuxthemer 
```sh
$flatpak list --app
Name           Application ID                      Version        Branch       Installation
Fondo          com.github.calo001.fondo            1.3.9          stable       user
Drawing        com.github.maoschanz.drawing        0.4.13         stable       user
```

**Comment by sandangel** [comment]
@paullinuxthemer you might want to take a look at Flat Remix theme, it handles the theme for pop shop perfectly. I notice that it has elementary OS variance and Pop Shop is just a fork of Elementary Software center

![image](https://user-images.githubusercontent.com/22189661/85229282-c7f81200-b423-11ea-8153-48da7e505258.png)
